Repository jenkins-x-apps/jx-app-cert-manager, pull requests merged in 2019-05, with the labels that each got.

#2 Moved jx-app-cert-manager into root of repo
  Makefile
  jx-app-cert-manager/.helmignore
  jx-app-cert-manager/Chart.yaml
  jx-app-cert-manager/charts/cert-manager-v0.7.1.tgz
  jx-app-cert-manager/requirements.lock
  jx-app-cert-manager/requirements.yaml
  jx-app-cert-manager/templates/NOTES.txt
  jx-app-cert-manager/templates/_helpers.tpl
  jx-app-cert-manager/values.schema.json
  jx-app-cert-manager/values.yaml
Labels: approved, size/XS

#3 Added gitignore
  .gitignore
  jx-app-cert-manager/charts/cert-manager-v0.7.1.tgz
  jx-app-cert-manager/requirements.lock
Labels: approved, size/S

#4 Added pre-install hook job to install CRDs
  jx-app-cert-manager/templates/pre-install-job.yaml
Labels: approved, size/S

#5 Add the validation to the correct namespace
  jx-app-cert-manager/templates/pre-install-job.yaml
Labels: approved, size/XS

#6 Updated crd pre-install hook file
  jx-app-cert-manager/templates/pre-install-job.yaml
Labels: approved, size/XS

#7 Added crd manifest for cert-manager 0.7.2
  jx-app-cert-manager/templates/crd-0.7.2.yaml
  jx-app-cert-manager/templates/pre-install-job.yaml
Labels: approved, size/XXL

#8 fix: removed bad indentation
  jx-app-cert-manager/templates/crd-0.7.2.yaml
Labels: approved, size/XS

#9 feat: Added 'crd-install' hook to all CRDs
  jx-app-cert-manager/templates/crd-0.7.2.yaml
Labels: approved, size/S

#10 fix: disabling validation on the namespace
  jx-app-cert-manager/templates/namespace.yaml
Labels: approved, lgtm, size/XS

#11 fix: templating the namespace
  jx-app-cert-manager/templates/namespace.yaml
Labels: approved, size/XS
